"use client";

import { useEffect, useRef, useState } from "react";
import {
  DAY_LABELS,
  formatTime,
  weekBounds,
  type Block,
  type Week,
} from "@/lib/schedule";

const PX_PER_MIN = 1; // 1 hour = 60px
const SNAP = 15; // drop snaps to 15-minute steps

const KIND_STYLES: Record<Block["kind"], string> = {
  fixed: "bg-zinc-800 text-white dark:bg-zinc-100 dark:text-zinc-900",
  flex: "bg-sky-500 text-white",
  want: "bg-emerald-500 text-white",
};

const KIND_LABEL: Record<Block["kind"], string> = {
  fixed: "Fixed",
  flex: "Activity",
  want: "Want",
};

type DragState = {
  di: number;
  bi: number;
  block: Block;
  grabX: number; // pointer offset inside the block
  grabY: number;
};

export function ScheduleGrid({
  week,
  title = "Your schedule",
  onBack,
  onEdit,
  onChange,
}: {
  week: Week;
  title?: string;
  onBack: () => void;
  onEdit: () => void;
  onChange: (week: Week) => void;
}) {
  const { start, end } = weekBounds(week);
  const totalMin = end - start;
  const height = totalMin * PX_PER_MIN;
  const hours: number[] = [];
  for (let m = start; m <= end; m += 60) hours.push(m);

  const isEmpty = week.every((d) => d.length === 0);

  // First day column, used to measure the grid geometry on drop.
  const colRef = useRef<HTMLDivElement | null>(null);
  const [drag, setDrag] = useState<DragState | null>(null);
  const [ghost, setGhost] = useState<{ x: number; y: number; w: number } | null>(
    null,
  );

  // While a drag is active, track the pointer and commit on release.
  useEffect(() => {
    if (!drag) return;

    function onMove(e: PointerEvent) {
      setGhost((g) =>
        g ? { ...g, x: e.clientX - drag!.grabX, y: e.clientY - drag!.grabY } : g,
      );
    }

    function onUp(e: PointerEvent) {
      const col = colRef.current;
      if (col) {
        const cr = col.getBoundingClientRect();
        const colW = cr.width;
        const duration = drag!.block.endMin - drag!.block.startMin;

        // Which day column did we drop over?
        const day = Math.max(
          0,
          Math.min(6, Math.floor((e.clientX - cr.left) / colW)),
        );
        // What start time, from the block's top edge, snapped to 15 min?
        const topY = e.clientY - drag!.grabY;
        const rawStart = start + (topY - cr.top) / PX_PER_MIN;
        const snapped = Math.round(rawStart / SNAP) * SNAP;
        const startMin = Math.max(start, Math.min(end - duration, snapped));

        const moved: Block = {
          ...drag!.block,
          startMin,
          endMin: startMin + duration,
        };
        const next: Week = week.map((d, di) =>
          di === drag!.di ? d.filter((_, bi) => bi !== drag!.bi) : d.slice(),
        );
        next[day] = [...next[day], moved].sort(
          (a, b) => a.startMin - b.startMin,
        );
        onChange(next);
      }
      setDrag(null);
      setGhost(null);
    }

    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
    return () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
    };
  }, [drag, week, start, end, onChange]);

  function startDrag(e: React.PointerEvent, di: number, bi: number) {
    e.preventDefault();
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    setDrag({
      di,
      bi,
      block: week[di][bi],
      grabX: e.clientX - rect.left,
      grabY: e.clientY - rect.top,
    });
    setGhost({ x: rect.left, y: rect.top, w: rect.width });
  }

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-4 px-3 py-6 sm:px-4 sm:py-8">
      <header className="flex items-center justify-between gap-2">
        <button
          type="button"
          onClick={onBack}
          aria-label="Back to lobby"
          className="flex h-10 w-10 items-center justify-center rounded-lg text-lg text-zinc-500 transition-colors hover:bg-black/[.05] hover:text-zinc-900 dark:hover:bg-white/[.08] dark:hover:text-white"
        >
          ←
        </button>
        <div className="flex flex-col items-center">
          <h1 className="max-w-[60vw] truncate text-base font-semibold tracking-tight">
            {title}
          </h1>
          <p className="text-xs text-zinc-400">Generated by ScheduleManager</p>
        </div>
        <button
          type="button"
          onClick={onEdit}
          aria-label="Edit survey"
          className="flex h-10 w-10 items-center justify-center rounded-lg text-base text-zinc-500 transition-colors hover:bg-black/[.05] hover:text-zinc-900 dark:hover:bg-white/[.08] dark:hover:text-white"
        >
          ✏️
        </button>
      </header>

      {/* Legend */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-zinc-500">
        {(["fixed", "flex", "want"] as const).map((k) => (
          <span key={k} className="flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${KIND_STYLES[k]}`} />
            {KIND_LABEL[k]}
          </span>
        ))}
        {!isEmpty && (
          <span className="text-zinc-400">· drag a block to move it</span>
        )}
      </div>

      {isEmpty ? (
        <div className="rounded-xl border border-black/[.08] p-8 text-center text-sm text-zinc-400 dark:border-white/[.1]">
          Nothing scheduled yet. Tap ✏️ to add programs and wants.
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-black/[.08] bg-white/60 dark:border-white/[.1] dark:bg-zinc-900/40">
          <div
            className="grid min-w-[640px]"
            style={{ gridTemplateColumns: "3rem repeat(7, minmax(76px, 1fr))" }}
          >
            {/* Header row */}
            <div className="sticky top-0 z-10 border-b border-black/[.08] bg-white/80 backdrop-blur dark:border-white/[.1] dark:bg-zinc-900/80" />
            {DAY_LABELS.map((d, i) => (
              <div
                key={d}
                className={`sticky top-0 z-10 border-b border-l border-black/[.06] bg-white/80 py-2 text-center text-xs font-medium backdrop-blur dark:border-white/[.08] dark:bg-zinc-900/80 ${
                  i >= 5 ? "text-zinc-400" : "text-zinc-700 dark:text-zinc-200"
                }`}
              >
                {d}
              </div>
            ))}

            {/* Time gutter */}
            <div className="relative" style={{ height }}>
              {hours.map((m) => (
                <div
                  key={m}
                  className="absolute right-1 text-[10px] leading-none tabular-nums text-zinc-400"
                  style={{ top: (m - start) * PX_PER_MIN + 2 }}
                >
                  {formatTime(m)}
                </div>
              ))}
            </div>

            {/* Day columns */}
            {week.map((day, di) => (
              <div
                key={di}
                ref={di === 0 ? colRef : undefined}
                className="relative border-l border-black/[.06] dark:border-white/[.08]"
                style={{ height }}
              >
                {hours.map((m) => (
                  <div
                    key={m}
                    className="absolute inset-x-0 border-t border-black/[.04] dark:border-white/[.05]"
                    style={{ top: (m - start) * PX_PER_MIN }}
                  />
                ))}
                {day.map((b, bi) => {
                  // Top edge = start time, bottom edge = end time (exact).
                  const top = (b.startMin - start) * PX_PER_MIN;
                  const h = (b.endMin - b.startMin) * PX_PER_MIN;
                  const isDragged =
                    drag !== null && drag.di === di && drag.bi === bi;
                  return (
                    <div
                      key={bi}
                      onPointerDown={(e) => startDrag(e, di, bi)}
                      className={`absolute inset-x-0.5 cursor-grab touch-none select-none overflow-hidden rounded-md px-1 py-0.5 text-[10px] leading-tight shadow-sm active:cursor-grabbing ${
                        KIND_STYLES[b.kind]
                      } ${isDragged ? "opacity-30" : ""}`}
                      style={{ top, height: h }}
                      title={`${b.title} · ${formatTime(b.startMin)}–${formatTime(b.endMin)}`}
                    >
                      <div className="truncate font-medium">{b.title}</div>
                      {h > 26 && (
                        <div className="truncate opacity-80">
                          {formatTime(b.startMin)}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Floating drag ghost */}
      {drag && ghost && (
        <div
          className={`pointer-events-none fixed z-50 overflow-hidden rounded-md px-1 py-0.5 text-[10px] leading-tight opacity-90 shadow-lg ${KIND_STYLES[drag.block.kind]}`}
          style={{
            left: ghost.x,
            top: ghost.y,
            width: ghost.w,
            height: (drag.block.endMin - drag.block.startMin) * PX_PER_MIN,
          }}
        >
          <div className="truncate font-medium">{drag.block.title}</div>
          <div className="truncate opacity-80">
            {formatTime(drag.block.startMin)}
          </div>
        </div>
      )}
    </main>
  );
}
