"use client";

import {
  DAY_LABELS,
  formatTime,
  weekBounds,
  type Block,
  type Week,
} from "@/lib/schedule";

const PX_PER_MIN = 0.75; // 1 hour ≈ 45px

const KIND_STYLES: Record<Block["kind"], string> = {
  fixed: "bg-zinc-800 text-white dark:bg-zinc-100 dark:text-zinc-900",
  flex: "bg-sky-500 text-white",
  want: "bg-emerald-500 text-white",
};

const KIND_LABEL: Record<Block["kind"], string> = {
  fixed: "Fixed",
  flex: "Activity",
  want: "Want",
};

export function ScheduleGrid({
  week,
  title = "Your schedule",
  onBack,
  onEdit,
}: {
  week: Week;
  title?: string;
  onBack: () => void;
  onEdit: () => void;
}) {
  const { start, end } = weekBounds(week);
  const totalMin = end - start;
  const height = totalMin * PX_PER_MIN;
  const hours: number[] = [];
  for (let m = start; m <= end; m += 60) hours.push(m);

  const isEmpty = week.every((d) => d.length === 0);

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-4 px-3 py-6 sm:px-4 sm:py-8">
      <header className="flex items-center justify-between gap-2">
        <button
          type="button"
          onClick={onBack}
          aria-label="Back to lobby"
          className="flex h-10 w-10 items-center justify-center rounded-lg text-lg text-zinc-500 transition-colors hover:bg-black/[.05] hover:text-zinc-900 dark:hover:bg-white/[.08] dark:hover:text-white"
        >
          ←
        </button>
        <div className="flex flex-col items-center">
          <h1 className="max-w-[60vw] truncate text-base font-semibold tracking-tight">
            {title}
          </h1>
          <p className="text-xs text-zinc-400">Generated by ScheduleManager</p>
        </div>
        <button
          type="button"
          onClick={onEdit}
          aria-label="Edit survey"
          className="flex h-10 w-10 items-center justify-center rounded-lg text-base text-zinc-500 transition-colors hover:bg-black/[.05] hover:text-zinc-900 dark:hover:bg-white/[.08] dark:hover:text-white"
        >
          ✏️
        </button>
      </header>

      {/* Legend */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-zinc-500">
        {(["fixed", "flex", "want"] as const).map((k) => (
          <span key={k} className="flex items-center gap-1.5">
            <span className={`h-2.5 w-2.5 rounded-full ${KIND_STYLES[k]}`} />
            {KIND_LABEL[k]}
          </span>
        ))}
      </div>

      {isEmpty ? (
        <div className="rounded-xl border border-black/[.08] p-8 text-center text-sm text-zinc-400 dark:border-white/[.1]">
          Nothing scheduled yet. Tap ✏️ to add programs and wants.
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-black/[.08] bg-white/60 dark:border-white/[.1] dark:bg-zinc-900/40">
          <div
            className="grid min-w-[640px]"
            style={{ gridTemplateColumns: "3rem repeat(7, minmax(76px, 1fr))" }}
          >
            {/* Header row */}
            <div className="sticky top-0 z-10 border-b border-black/[.08] bg-white/80 backdrop-blur dark:border-white/[.1] dark:bg-zinc-900/80" />
            {DAY_LABELS.map((d, i) => (
              <div
                key={d}
                className={`sticky top-0 z-10 border-b border-l border-black/[.06] bg-white/80 py-2 text-center text-xs font-medium backdrop-blur dark:border-white/[.08] dark:bg-zinc-900/80 ${
                  i >= 5 ? "text-zinc-400" : "text-zinc-700 dark:text-zinc-200"
                }`}
              >
                {d}
              </div>
            ))}

            {/* Time gutter */}
            <div className="relative" style={{ height }}>
              {hours.map((m) => (
                <div
                  key={m}
                  className="absolute right-1 -translate-y-1/2 text-[10px] tabular-nums text-zinc-400"
                  style={{ top: (m - start) * PX_PER_MIN }}
                >
                  {formatTime(m)}
                </div>
              ))}
            </div>

            {/* Day columns */}
            {week.map((day, di) => (
              <div
                key={di}
                className="relative border-l border-black/[.06] dark:border-white/[.08]"
                style={{ height }}
              >
                {hours.map((m) => (
                  <div
                    key={m}
                    className="absolute inset-x-0 border-t border-black/[.04] dark:border-white/[.05]"
                    style={{ top: (m - start) * PX_PER_MIN }}
                  />
                ))}
                {day.map((b, bi) => {
                  const top = (b.startMin - start) * PX_PER_MIN;
                  const h = Math.max((b.endMin - b.startMin) * PX_PER_MIN, 16);
                  return (
                    <div
                      key={bi}
                      className={`absolute inset-x-0.5 overflow-hidden rounded-md px-1 py-0.5 text-[10px] leading-tight shadow-sm ${KIND_STYLES[b.kind]}`}
                      style={{ top, height: h }}
                      title={`${b.title} · ${formatTime(b.startMin)}–${formatTime(b.endMin)}`}
                    >
                      <div className="truncate font-medium">{b.title}</div>
                      {h > 26 && (
                        <div className="truncate opacity-80">
                          {formatTime(b.startMin)}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            ))}
          </div>
        </div>
      )}
    </main>
  );
}
